version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
